version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
        - ./postgres-db-data:/var/lib/postgresql/data